apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
  namespace: digitalleman
spec:
  selector:
    matchLabels:
      app: calendar
  replicas: 1
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
      - name: calendar
        image: quentinburgniard/calendar
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calendar
  namespace: digitalleman
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80